<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-QJHRQ4H" name="online_tusur.unit_online_tusur.StudTestNG" tests="16" failures="2" timestamp="2023-03-20T23:04:54 MSK" time="1.222" errors="0">
  <testcase name="test3" time="0.076" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
  <testcase name="test1" time="0.071" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
  <testcase name="test1" time="0.068" classname="online_tusur.unit_online_tusur.StudTestNG">
    <failure type="java.lang.AssertionError" message="expected:&lt;K&gt; but was:&lt;k&gt;">
      <![CDATA[java.lang.AssertionError: expected:<K> but was:<k>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at online_tusur.unit_online_tusur.StudTestNG.test1(StudTestNG.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase name="test_name" time="0.093" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
  <testcase name="test_MIN" time="0.081" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
  <testcase name="test2" time="0.077" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
  <testcase name="test3" time="0.072" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
  <testcase name="test_AVG" time="0.082" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
  <testcase name="test3" time="0.077" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
  <testcase name="test1" time="0.075" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
  <testcase name="test1" time="0.069" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
  <testcase name="test2" time="0.075" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
  <testcase name="test_MAX" time="0.079" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
  <testcase name="test2" time="0.075" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
  <testcase name="test3" time="0.078" classname="online_tusur.unit_online_tusur.StudTestNG">
    <failure type="java.lang.AssertionError" message="expected:&lt;50&gt; but was:&lt;18&gt;">
      <![CDATA[java.lang.AssertionError: expected:<50> but was:<18>
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:468)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:318)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:328)
at online_tusur.unit_online_tusur.StudTestNG.test3(StudTestNG.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase name="test2" time="0.074" classname="online_tusur.unit_online_tusur.StudTestNG"/>
  <system-out/>
</testsuite> <!-- online_tusur.unit_online_tusur.StudTestNG -->
